// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recomandare_PC.Data;

#nullable disable

namespace Recomandare_PC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317151407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recomandare_PC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PSU"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cooler"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Case"
                        });
                });

            modelBuilder.Entity("Recomandare_PC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Recomandare_PC.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            Name = "Aer"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Name = "Lichid"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Name = "SSD NVMe"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            Name = "SSD SATA"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Name = "HDD"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "DDR4"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "DDR5"
                        });
                });

            modelBuilder.Entity("Recomandare_PC.Models.Product", b =>
                {
                    b.HasOne("Recomandare_PC.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recomandare_PC.Models.Subcategory", "Subcategory")
                        .WithMany("Products")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("Recomandare_PC.Models.Subcategory", b =>
                {
                    b.HasOne("Recomandare_PC.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Recomandare_PC.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Recomandare_PC.Models.Subcategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
